server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/travel?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
  thymeleaf:
    cache: true
  redis:
    jedis:
      pool:
        max-active: 10
        max-wait: 1000ms
        max-idle: 8
        min-idle: 5
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

mybatis-plus:
  type-aliases-package: com.zcq.travelweb.Mapper
  mapper-locations: classpath:mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: false

